### ISSUE TITLE
Local data store for longer retention periods

### ISSUE THREAD

**Issue by jgarman** [carbonblack/cb-threatexchange-connector#2]
We will want to expand our retention period without re-requesting records from the ThreatExchange. Create a local datastore to keep those records and only request "new" ones for the past day (or other configurable time period)

**Comment by mtmcgrew** [comment]
This would be great

**Comment by RyPeck** [comment]
Perhaps locally with Pickle, JSON or SQLite?

**Comment by jgarman** [comment]
This is in progress now and will be part of the next release. It will use a local SQLite database to retain all data for a configurable amount of time then perform the filtering and grouping before generating the feed for Carbon Black.

**Comment by RyPeck** [comment]
@jgarman :+1:
