### ISSUE TITLE
pytx access_token got changed

### ISSUE THREAD

**Issue by mgoffin** [carbonblack/cb-threatexchange-connector#3]
I just made a change to `pytx` for `v0.3.0` which is now on `PyPi` which I think breaks the threatexchange-connector.

https://github.com/carbonblack/cb-threatexchange-connector/blob/master/cbopensource/connectors/threatexchange/bridge.py#L214

You now need to call `access_token.access_token()` instead:

https://github.com/facebook/ThreatExchange/blob/master/pytx/pytx/access_token.py#L54

I don't know if you have a locked version of pytx which would mean you can ignore this, but I wanted to let you know just in case!

**Comment by jgarman** [comment]
Thanks for providing the heads up and the patch, @mgoffin
